# Generated by Django 5.2.3 on 2025-08-20 21:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientCategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Plat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("lieu", models.CharField(max_length=100)),
                ("population", models.CharField(default="patients", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("unite", models.CharField(max_length=20)),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="Restauration.ingredientcategorie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuSupplementaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_chambre", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "date",
                    models.DateField(
                        blank=True, default=datetime.date.today, null=True
                    ),
                ),
                (
                    "repas",
                    models.CharField(
                        choices=[
                            ("Petit déjeuner", "Petit déjeuner (07h00)"),
                            ("Déjeuner", "Déjeuner (12h30)"),
                            ("Collation", "Collation (16h30)"),
                            ("Dîner", "Dîner (20h00)"),
                        ],
                        default="Petit déjeuner",
                        max_length=20,
                    ),
                ),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patient.patient",
                        verbose_name="Client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, default=datetime.date.today, null=True
                    ),
                ),
                (
                    "repas",
                    models.CharField(
                        choices=[
                            ("Petit déjeuner", "Petit déjeuner (07h00)"),
                            ("Déjeuner", "Déjeuner (12h30)"),
                            ("Collation", "Collation (16h30)"),
                            ("Dîner", "Dîner (20h00)"),
                        ],
                        default="Petit déjeuner",
                        max_length=20,
                    ),
                ),
                ("plats", models.ManyToManyField(to="Restauration.plat")),
            ],
        ),
        migrations.CreateModel(
            name="MenuPersonnalise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_chambre", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "date",
                    models.DateField(
                        blank=True, default=datetime.date.today, null=True
                    ),
                ),
                (
                    "repas",
                    models.CharField(
                        choices=[
                            ("Petit déjeuner", "Petit déjeuner (07h00)"),
                            ("Déjeuner", "Déjeuner (12h30)"),
                            ("Collation", "Collation (16h30)"),
                            ("Dîner", "Dîner (20h00)"),
                        ],
                        default="Petit déjeuner",
                        max_length=50,
                    ),
                ),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description ou remarques spéciales"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patient.patient",
                        verbose_name="Client",
                    ),
                ),
                ("plats", models.ManyToManyField(to="Restauration.plat")),
            ],
        ),
        migrations.CreateModel(
            name="ProgrammeJour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restauration.menustandard",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jours",
                        to="Restauration.programme",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("programme", "date")},
            },
        ),
        migrations.CreateModel(
            name="ProgrammeJourMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heure_service",
                    models.TimeField(
                        help_text="Heure à laquelle le menu sera servi",
                        verbose_name="Heure de service",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Notes spéciales pour ce menu",
                        verbose_name="Description/Remarques",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "plats",
                    models.ManyToManyField(
                        to="Restauration.plat", verbose_name="Plats sélectionnés"
                    ),
                ),
                (
                    "programme_jour",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_personnalise",
                        to="Restauration.programmejour",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu du jour de programme",
                "verbose_name_plural": "Menus des jours de programme",
            },
        ),
        migrations.CreateModel(
            name="Recette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recette",
                        to="Restauration.plat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LigneRecette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_par_portion",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restauration.ingredient",
                    ),
                ),
                (
                    "recette",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_recette",
                        to="Restauration.recette",
                    ),
                ),
            ],
        ),
    ]
