# Generated by Django 5.2.3 on 2025-08-20 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="recruitment/candidates/photos/",
                    ),
                ),
                (
                    "linkedin_profile",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("archived", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_date", models.DateTimeField()),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("always_available", models.BooleanField(default=False)),
                ("availability_start", models.DateField(blank=True, null=True)),
                ("availability_end", models.DateField(blank=True, null=True)),
                (
                    "cv",
                    models.FileField(
                        blank=True, null=True, upload_to="recruitment/applications/cv/"
                    ),
                ),
                (
                    "cover_letter",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="recruitment/applications/cover_letters/",
                    ),
                ),
                (
                    "certificates",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="recruitment/applications/certificates/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("in_review", "In Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recruitment.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evaluation_date", models.DateField(auto_now_add=True)),
                (
                    "work_quality",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Qualité du travail",
                    ),
                ),
                (
                    "deadline_respect",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Respect des délais",
                    ),
                ),
                (
                    "team_spirit",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Esprit d'équipe",
                    ),
                ),
                (
                    "autonomy",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Autonomie",
                    ),
                ),
                (
                    "initiative",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Capacité d'initiative",
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, null=True, verbose_name="Commentaires du supérieur"
                    ),
                ),
                (
                    "improvement_plan",
                    models.TextField(
                        blank=True, null=True, verbose_name="Plan d'amélioration"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("submitted", "Soumis"),
                            ("validated", "Validé"),
                            ("signed", "Signé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "hr_validation",
                    models.BooleanField(default=False, verbose_name="Validation RH"),
                ),
                ("hr_validation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "employee_notified",
                    models.BooleanField(default=False, verbose_name="Salarié notifié"),
                ),
                ("notification_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="hr.employee",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations_given",
                        to="hr.employee",
                    ),
                ),
                (
                    "hr_validator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_validations",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation",
                "verbose_name_plural": "Évaluations",
                "ordering": ["-evaluation_date"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "videcall_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("pending", "Pending"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("reception", "Réception de l'offre"),
                            ("a", "Entretien A"),
                            ("b", "Entretien B"),
                        ],
                        default="reception",
                        max_length=20,
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recruitment.application",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_interviews",
                        to="hr.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("publication_date", models.DateField()),
                ("end_date", models.DateField()),
                ("skills", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.TextField(
                        blank=True, null=True, verbose_name="Profil recherché"
                    ),
                ),
                (
                    "positions_available",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre de postes"
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.department",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recruitment.offer"
            ),
        ),
        migrations.CreateModel(
            name="Pointage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("jour", models.CharField(max_length=20)),
                ("heure_arrivee", models.TimeField()),
                ("heure_depart", models.TimeField()),
                ("heure_travaillee", models.DurationField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages",
                        to="hr.employee",
                    ),
                ),
            ],
        ),
    ]
