# Generated by Django 5.2.3 on 2025-08-20 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BedStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Statut de lit",
                "verbose_name_plural": "Statuts de lit",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("room_name", models.CharField(max_length=100, unique=True)),
                ("capacity", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("occupied", "Occupée"),
                            ("maintenance", "En maintenance"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Room Type",
                "verbose_name_plural": "Room Types",
            },
        ),
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "bed_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("bed_number", models.CharField(max_length=50)),
                (
                    "bed_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beds",
                        to="hosting.bedstatus",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beds",
                        to="hosting.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lit",
                "verbose_name_plural": "Lits",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("reservation_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "reservation_status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmé"),
                            ("cancelled", "Annulé"),
                            ("pending", "En attente"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "bed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="hosting.bed",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="patient.patient",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="hosting.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
            },
        ),
        migrations.CreateModel(
            name="Companion",
            fields=[
                ("companion_id", models.AutoField(primary_key=True, serialize=False)),
                ("companion_name", models.CharField(max_length=100)),
                ("relationship", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("accommodation_start_date", models.DateField(blank=True, null=True)),
                ("accommodation_end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "bed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companions",
                        to="hosting.bed",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companions",
                        to="patient.patient",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companions",
                        to="hosting.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Companion",
                "verbose_name_plural": "Companions",
            },
        ),
        migrations.CreateModel(
            name="Admission",
            fields=[
                ("admission_id", models.AutoField(primary_key=True, serialize=False)),
                ("admission_date", models.DateField()),
                (
                    "assignment_mode",
                    models.CharField(
                        choices=[("bed", "Lit"), ("room", "Chambre entière")],
                        max_length=20,
                    ),
                ),
                ("room_type", models.CharField(max_length=50)),
                ("discharge_date", models.DateField(blank=True, null=True)),
                (
                    "discharge_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("end_of_stay", "Fin de séjour"),
                            ("transfer", "Transfert"),
                            ("death", "Décès"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions",
                        to="patient.consultation",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions",
                        to="patient.patient",
                    ),
                ),
                (
                    "bed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions",
                        to="hosting.bed",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions",
                        to="hosting.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admission",
                "verbose_name_plural": "Admissions",
            },
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms",
                to="hosting.roomtype",
            ),
        ),
    ]
