# Generated by Django 5.2.3 on 2025-08-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='discharge_reason',
            field=models.CharField(blank=True, choices=[('healed', 'Guérison'), ('death', 'Décès'), ('transfer', 'Transfert'), ('against_advice', 'Sortie contre avis'), ('abandonment', 'Abandon'), ('escape', 'Fugue')], max_length=20, null=True),
        ),
    ]
