# Generated by Django 5.2.3 on 2025-08-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_alter_admission_discharge_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='discharge_reason',
            field=models.CharField(blank=True, choices=[('end_of_stay', 'Fin de séjour'), ('transfer', 'Transfert'), ('death', 'Décès')], max_length=20, null=True),
        ),
    ]
