# Generated by Django 5.2.3 on 2025-08-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0003_alter_admission_discharge_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Accompagnant', max_length=100, unique=True)),
                ('daily_price', models.DecimalField(decimal_places=2, default=200, max_digits=10, verbose_name='Prix par jour')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Accompagnant',
                'verbose_name_plural': 'Services Accompagnant',
            },
        ),
        migrations.AddField(
            model_name='roomtype',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix par jour'),
        ),
    ]
