# Generated by Django 5.2.3 on 2025-08-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0004_companionservice_roomtype_daily_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanionService',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='daily_price',
        ),
    ]
