# Generated by Django 5.2.3 on 2025-08-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0005_delete_companionservice_remove_roomtype_daily_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='is_invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
