# Generated by Django 5.2.3 on 2025-08-20 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("formation", "0001_initial"),
        ("hr", "0001_initial"),
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formation",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formations",
                to="purchases.supplier",
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hr.employee"
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="inscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="formation.inscription"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="formateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="formation.formateur"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="formation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="formation.formation"
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="formation.session"
            ),
        ),
    ]
