# Generated by Django 5.2.3 on 2025-08-27 11:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('chambre', models.CharField(blank=True, max_length=10, verbose_name='Chambre')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Prestataire',
                'verbose_name_plural': 'Prestataires',
            },
        ),
        migrations.CreateModel(
            name='Priorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('niveau', models.PositiveSmallIntegerField(default=0, help_text='Ordre de tri')),
            ],
            options={
                'verbose_name': 'Priorité',
                'verbose_name_plural': 'Priorités',
                'ordering': ['niveau'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image')),
                ('type_demande', models.CharField(choices=[('Interne', 'Interne'), ('Patient', 'Patient')], max_length=20, verbose_name='Type de demande')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('couleur', models.CharField(blank=True, help_text='CSS class: success, warning, danger', max_length=20)),
                ('category', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminée'), ('cancelled', 'Annulée'), ('pending', 'En attente')], default='active', help_text='Utilisé pour le regroupement dans les statistiques', max_length=20)),
            ],
            options={
                'verbose_name': 'Statut',
                'verbose_name_plural': 'Statuts',
            },
        ),
        migrations.CreateModel(
            name='DemandePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_souhaitee', models.DateTimeField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandes.patient', verbose_name='Patient')),
                ('prestataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demandes.prestataire')),
                ('priorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandes.priorite')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandes.statut')),
            ],
            options={
                'verbose_name': 'Demande Patient',
                'verbose_name_plural': 'Demandes Patient',
            },
        ),
        migrations.CreateModel(
            name='DemandeInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_souhaitee', models.DateTimeField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('departement_destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_internes_recues', to='demandes.department', verbose_name='Département destinataire')),
                ('departement_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_internes_envoyees', to='demandes.department', verbose_name='Département source')),
                ('prestataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demandes.prestataire')),
                ('priorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandes.priorite')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandes.statut')),
            ],
            options={
                'verbose_name': 'Demande Interne',
                'verbose_name_plural': 'Demandes Internes',
            },
        ),
        migrations.CreateModel(
            name='DemandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('demande_interne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_dans_demande', to='demandes.demandeinterne')),
                ('demande_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_dans_demande', to='demandes.demandepatient')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandes.produit')),
            ],
            options={
                'verbose_name': 'Produit dans demande',
                'verbose_name_plural': 'Produits dans demandes',
            },
        ),
    ]
