# Generated by Django 5.2.3 on 2025-08-27 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeinterne',
            name='departement_destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_internes_recues', to='hr.department', verbose_name='Département destinataire'),
        ),
        migrations.AlterField(
            model_name='demandeinterne',
            name='departement_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_internes_envoyees', to='hr.department', verbose_name='Département source'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
