# Generated by Django 5.2.3 on 2025-09-26 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_alter_demandeinterne_departement_destinataire_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepatient',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.supplier'),
        ),
        migrations.AlterField(
            model_name='demandeinterne',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.supplier'),
        ),
        migrations.DeleteModel(
            name='Prestataire',
        ),
    ]
