# Generated by Django 5.2.3 on 2025-09-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0003_alter_demandepatient_prestataire_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='DemandePatientModel',
        ),
    ]
