# Generated by Django 5.2.3 on 2025-08-20 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("categ_id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "inventory_category",
            },
        ),
        migrations.CreateModel(
            name="LocationType",
            fields=[
                (
                    "location_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "inventory_locationType",
            },
        ),
        migrations.CreateModel(
            name="OperationType",
            fields=[
                (
                    "operation_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "inventory_operationType",
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "product_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "inventory_productType",
            },
        ),
        migrations.CreateModel(
            name="UnitOfMesure",
            fields=[
                ("uom_id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=50, unique=True)),
                ("symbole", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "inventory_unitofmesure",
            },
        ),
        migrations.CreateModel(
            name="InventoryProductDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_stored",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_products",
                        to="hr.department",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_product_department",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "default_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "standard_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "image_1920",
                    models.ImageField(
                        blank=True, null=True, upload_to="inventory_img/"
                    ),
                ),
                ("weight", models.FloatField(default=0)),
                ("volume", models.FloatField(default=0)),
                ("dlc", models.DateField(blank=True, null=True)),
                ("stock_minimal", models.IntegerField(default=0)),
                (
                    "total_quantity_cached",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "categ",
                    models.ForeignKey(
                        blank=True,
                        db_column="categ_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.category",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="inventory_products",
                        through="inventory.InventoryProductDepartment",
                        to="hr.department",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="product_type_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.producttype",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_product",
            },
        ),
        migrations.CreateModel(
            name="LineStockMove",
            fields=[
                ("line_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity_demanded",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "quantity_arrived",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="move_lines",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de mouvement",
                "verbose_name_plural": "Lignes de mouvement",
                "db_table": "inventory_line_stock_move",
            },
        ),
        migrations.AddField(
            model_name="inventoryproductdepartment",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_departments",
                to="inventory.product",
            ),
        ),
        migrations.CreateModel(
            name="StockLocation",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "location_type",
                    models.ForeignKey(
                        db_column="location_type_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.locationtype",
                    ),
                ),
                (
                    "parent_location",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_location_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="inventory.stocklocation",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_stockLocation",
            },
        ),
        migrations.CreateModel(
            name="ProductLocation",
            fields=[
                (
                    "product_location_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "quantity_stored",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Physical quantity currently on hand",
                        max_digits=12,
                    ),
                ),
                (
                    "last_count_date",
                    models.DateField(
                        blank=True, help_text="Date of the last stock count", null=True
                    ),
                ),
                (
                    "quantity_counted",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Physical quantity counted during inventory",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_locations",
                        to="inventory.product",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        db_column="location_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_locations",
                        to="inventory.stocklocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product / Location",
                "verbose_name_plural": "Products / Locations",
                "db_table": "inventory_product_location",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="locations",
            field=models.ManyToManyField(
                related_name="products",
                through="inventory.ProductLocation",
                to="inventory.stocklocation",
            ),
        ),
        migrations.CreateModel(
            name="StockMove",
            fields=[
                ("move_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("confirmed", "Confirmé"),
                            ("done", "Terminé"),
                            ("canceled", "Annulé"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(max_length=64, unique=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_moves",
                        to="hr.department",
                    ),
                ),
                (
                    "dest_location",
                    models.ForeignKey(
                        blank=True,
                        db_column="dest_location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves_to",
                        to="inventory.stocklocation",
                    ),
                ),
                (
                    "operation_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="operation_type_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.operationtype",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="stock_moves",
                        through="inventory.LineStockMove",
                        to="inventory.product",
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        blank=True,
                        db_column="source_location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves_from",
                        to="inventory.stocklocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "db_table": "inventory_stockMove",
                "ordering": ["-scheduled_date"],
            },
        ),
    ]
