# Generated by Django 5.2.3 on 2025-08-20 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmove",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                db_column="supplier_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_moves",
                to="purchases.supplier",
            ),
        ),
        migrations.AddField(
            model_name="linestockmove",
            name="move",
            field=models.ForeignKey(
                db_column="move_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="inventory.stockmove",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="uom",
            field=models.ForeignKey(
                blank=True,
                db_column="uom_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.unitofmesure",
            ),
        ),
        migrations.AddField(
            model_name="linestockmove",
            name="uom",
            field=models.ForeignKey(
                db_column="uom_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.unitofmesure",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventoryproductdepartment",
            unique_together={("product", "department")},
        ),
        migrations.AlterUniqueTogether(
            name="productlocation",
            unique_together={("product", "location")},
        ),
    ]
