# Generated by Django 5.2.3 on 2025-07-13 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_convention_type_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('date_acquisition', models.DateField()),
                ('emplacement', models.CharField(max_length=255)),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('bon', 'Bon état'), ('moyen', 'État moyen'), ('mauvais', 'Mauvais état'), ('hors_service', 'Hors service')], default='bon', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('motif_visite', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_incident', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ouvert', max_length=20)),
                ('gravite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], default='faible', max_length=20)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='maintenance.equipement')),
            ],
        ),
    ]
