# Generated by Django 5.2.3 on 2025-07-14 00:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_equipement_visiteur_incident'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-date_declaration']},
        ),
        migrations.AlterModelOptions(
            name='visiteur',
            options={'ordering': ['-date_entree'], 'verbose_name': 'Visiteur', 'verbose_name_plural': 'Visiteurs'},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='date_incident',
        ),
        migrations.AddField(
            model_name='incident',
            name='date_declaration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('panne', 'Panne'), ('maintenance', 'Maintenance'), ('accident', 'Accident'), ('defaillance', 'Défaillance')], default='panne', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='date_entree',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'entrée"),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='date_sortie',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='motif_visite',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de visite'),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='prenom',
            field=models.CharField(max_length=255, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
