# Generated by Django 5.2.3 on 2025-07-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_incident_options_alter_visiteur_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='conventions/'),
        ),
    ]
