# Generated by Django 5.2.3 on 2025-07-17 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_convention_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateTimeField()),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='planifiee', max_length=20)),
                ('observation', models.TextField(blank=True, null=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.equipement')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.incident')),
                ('prestataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.prestataire')),
            ],
            options={
                'ordering': ['-date_intervention'],
            },
        ),
    ]
