# Generated by Django 5.2.3 on 2025-07-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_intervention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='description',
        ),
    ]
