# Generated by Django 5.2.3 on 2025-07-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_remove_intervention_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervention',
            old_name='observation',
            new_name='description',
        ),
    ]
