# Generated by Django 5.2.3 on 2025-07-17 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_rename_observation_intervention_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervention',
            options={},
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='incident',
        ),
    ]
