# Generated by Django 5.2.3 on 2025-07-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_alter_intervention_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
