# Generated by Django 5.2.3 on 2025-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_alter_convention_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='type_intervention',
            field=models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective'), ('inspection', 'Inspection'), ('autre', 'Autre')], default='preventive', max_length=20),
        ),
        migrations.AlterField(
            model_name='convention',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='conventions/'),
        ),
    ]
