# Generated by Django 5.2.3 on 2025-08-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_alter_convention_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='conventions/'),
        ),
    ]
