# Generated by Django 5.2.3 on 2025-07-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_intervention_type_intervention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='criticite',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], default='moyenne', max_length=10),
        ),
        migrations.AddField(
            model_name='intervention',
            name='obligatoire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intervention',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='statut',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('en_attente', 'En attente'), ('terminee', 'Terminée')], default='planifiee', max_length=20),
        ),
    ]
