# Generated by Django 5.2.3 on 2025-07-24 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_intervention_criticite_intervention_obligatoire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='obligatoire',
        ),
    ]
