# Generated by Django 5.2.3 on 2025-07-25 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_alter_intervention_options_intervention_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.incident'),
        ),
    ]
