# Generated by Django 5.2.3 on 2025-07-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_alter_intervention_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='type_intervention',
            field=models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective')], default='preventive', max_length=20),
        ),
    ]
