# Generated by Django 5.2.3 on 2025-07-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_service_incident_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='service',
        ),
    ]
