# Generated by Django 5.2.3 on 2025-07-31 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_remove_intervention_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.service'),
        ),
    ]
