# Generated by Django 5.2.3 on 2025-08-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_alter_convention_fichier'),
        ('maintenance', '0019_intervention_service'),
    ]

    operations = [
    ]
