# Generated by Django 5.2.3 on 2025-08-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_merge_20250801_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='service',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='intervention',
            options={},
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='incident',
        ),
        migrations.AlterField(
            model_name='intervention',
            name='statut',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='planifiee', max_length=20),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
