# Generated by Django 5.2.3 on 2025-08-22 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_remove_incident_service_remove_intervention_service_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='prestataire',
        ),
        migrations.RemoveField(
            model_name='convention',
            name='prestataire',
        ),
        migrations.AddField(
            model_name='convention',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conventions', to='purchases.supplier'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.supplier'),
        ),
        migrations.DeleteModel(
            name='Prestataire',
        ),
    ]
