# Generated by Django 5.2.3 on 2025-09-26 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0022_add_supplier_fields'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervention',
            options={'ordering': ['-date_intervention']},
        ),
        migrations.AddField(
            model_name='visiteur',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='visiteurs_qr/', verbose_name='Code QR'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_conventions', to='purchases.supplier'),
        ),
    ]
