# Generated by Django 4.2.23 on 2025-10-15 18:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('is_scolarise', models.BooleanField(default=False, verbose_name='Scolarisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='hr.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hr_media/employees_profile/')),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('personal_phone', models.CharField(max_length=20)),
                ('work_phone', models.CharField(max_length=20)),
                ('personal_address', models.TextField(blank=True, null=True)),
                ('work_address', models.TextField(blank=True, null=True)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1)),
                ('work_certificate', models.FileField(blank=True, null=True, upload_to='hr_media/certificates/')),
                ('legalized_contract', models.FileField(blank=True, null=True, upload_to='hr_media/legalized_contracts/')),
                ('doctor_agreement', models.FileField(blank=True, null=True, upload_to='hr_media/doctor_agreements/')),
                ('temporary_agreement', models.FileField(blank=True, null=True, upload_to='hr_media/temporary_agreements/')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('career_evolution', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('is_supervisor', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='hr.child')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('default_days', models.DecimalField(blank=True, decimal_places=2, help_text='Nombre de jours attribués par défaut (optionnel)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jours par défaut')),
                ('accrual_method', models.CharField(choices=[('annual', 'Annuel'), ('monthly', 'Mensuel')], default='annual', help_text='Comment les jours de congé sont accumulés', max_length=10, verbose_name="Méthode d'acquisition")),
                ('year', models.IntegerField(blank=True, help_text='Année pour laquelle ce type de congé est applicable', null=True, verbose_name='Année')),
                ('active', models.BooleanField(default=True, help_text='Indique si ce type de congé est actuellement actif', verbose_name='Actif')),
                ('monday', models.BooleanField(default=True, verbose_name='Lundi')),
                ('tuesday', models.BooleanField(default=True, verbose_name='Mardi')),
                ('wednesday', models.BooleanField(default=True, verbose_name='Mercredi')),
                ('thursday', models.BooleanField(default=True, verbose_name='Jeudi')),
                ('friday', models.BooleanField(default=True, verbose_name='Vendredi')),
                ('saturday', models.BooleanField(default=False, verbose_name='Samedi')),
                ('sunday', models.BooleanField(default=False, verbose_name='Dimanche')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Type de congé',
                'verbose_name_plural': 'Types de congés',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Taux en pourcentage', max_digits=7, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Montant de la prime', max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ceiling', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_nom', models.CharField(max_length=100)),
                ('type_sortie', models.CharField(choices=[('DEMISSION', 'Démission'), ('RETRAITE', 'Départ à la retraite'), ('LICENCIEMENT', 'Licenciement')], max_length=20)),
                ('motif', models.TextField()),
                ('date_sortie', models.DateField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='sorties/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sortie',
                'verbose_name_plural': 'Sorties',
                'ordering': ['-date_sortie'],
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la spécialité')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollGenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls_generated_for', to='hr.employee')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls_generated_by', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCalcul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('primes', models.ManyToManyField(blank=True, to='hr.prime')),
                ('social_contributions', models.ManyToManyField(blank=True, to='hr.socialcontribution')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255, verbose_name='Nom du médecin')),
                ('visit_date', models.DateField(verbose_name='Date de visite')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='hr_media/medical_results/', verbose_name='Résultat de visite (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_visits', to='hr.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Visite médicale',
                'verbose_name_plural': 'Visites médicales',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('approved', 'Approuvé'), ('refused', 'Refusé'), ('canceled', 'Annulé')], default='draft', max_length=10, verbose_name='Statut')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='leave_certificates/', verbose_name='Certificat médical')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('selected_days', models.TextField(blank=True, help_text='Liste des dates sélectionnées au format JSON', null=True, verbose_name='Jours sélectionnés')),
                ('manager_decision', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('refused', 'Refusé')], default='pending', max_length=10, verbose_name='Décision chef')),
                ('manager_decision_date', models.DateTimeField(blank=True, null=True, verbose_name='Date décision chef')),
                ('manager_comments', models.TextField(blank=True, null=True, verbose_name='Commentaires chef')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee', verbose_name='Employé')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hr.leavetype', verbose_name='Type de congé')),
                ('manager_decider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_decisions', to='hr.employee', verbose_name='Chef décideur')),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congés',
                'db_table': 'hr_leave_request',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approuvé'), ('refused', 'Refusé')], max_length=10, verbose_name='Décision')),
                ('decision_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de décision')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_approvals', to='hr.employee', verbose_name='Approbateur')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='hr.leaverequest', verbose_name='Demande de congé')),
            ],
            options={
                'verbose_name': 'Approbation de congé',
                'verbose_name_plural': 'Approbations de congés',
                'db_table': 'hr_leave_approval',
                'ordering': ['-decision_date'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='model_calcul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.modelcalcul'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.speciality', verbose_name='Spécialité'),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hr.employee'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.contracttype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('entitlement', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('taken', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='hr.leavetype')),
            ],
            options={
                'db_table': 'hr_leave_balance',
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
