# Generated by Django 5.2.3 on 2025-08-24 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_invoiced',
            field=models.BooleanField(default=False, verbose_name='Facturée'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='N° Facture')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('invoice_date', models.DateField(auto_now_add=True, verbose_name='Date facture')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Date échéance')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('overdue', 'En retard')], default='draft', max_length=10, verbose_name='Statut')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant payé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='patient.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_date'],
            },
        ),
    ]
