# Generated by Django 5.2.3 on 2025-08-24 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_consultation_is_invoiced_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='patient.consultation'),
        ),
    ]
