# Generated by Django 5.2.3 on 2025-10-09 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('patient', '0004_billinghistory'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date_heure'], 'verbose_name': 'Rendez-vous', 'verbose_name_plural': 'Rendez-vous'},
        ),
        migrations.AddField(
            model_name='consultation',
            name='consigne_alimentaire',
            field=models.TextField(blank=True, help_text='Instructions alimentaires spécifiques', verbose_name='Consigne alimentaire'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='consigne_hebergement',
            field=models.TextField(blank=True, help_text="Instructions pour l'hébergement du patient", verbose_name="Consigne d'hébergement"),
        ),
        migrations.AddField(
            model_name='consultation',
            name='date_admission_programmee',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'admission programmée"),
        ),
        migrations.AddField(
            model_name='consultation',
            name='demande_patient',
            field=models.CharField(choices=[('consultation_normale', 'Consultation normale'), ('hospitalisation', 'Hospitalisation')], default='consultation_normale', max_length=20, verbose_name='Demande de patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='type_admission',
            field=models.CharField(blank=True, choices=[('immediate', 'Admission immédiate (urgence)'), ('programmee', 'Admission programmée (planifié)')], max_length=20, null=True, verbose_name="Type d'admission"),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='hr.employee', verbose_name='Médecin'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='patient.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='traitement',
            field=models.TextField(blank=True, help_text='Instructions de traitement générales', verbose_name='Traitement'),
        ),
        migrations.CreateModel(
            name='MedicationPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(help_text='Quantité exacte à administrer à chaque prise (ex: 500mg, 1 comprimé, 5ml)', max_length=100, verbose_name='Dose')),
                ('frequence', models.CharField(choices=[('1x', '1 fois par jour'), ('2x', '2 fois par jour'), ('3x', '3 fois par jour'), ('4x', '4 fois par jour'), ('6x', '6 fois par jour'), ('8x', '8 fois par jour'), ('12x', 'Toutes les 12 heures'), ('24x', 'Toutes les 24 heures'), ('48x', 'Toutes les 48 heures'), ('semaine', '1 fois par semaine'), ('2semaines', '1 fois toutes les 2 semaines'), ('mois', '1 fois par mois'), ('as_needed', 'Selon les besoins')], help_text='Nombre de prises par jour ou intervalle entre deux prises', max_length=20, verbose_name='Fréquence')),
                ('duree', models.CharField(help_text='Période totale du traitement (ex: 7 jours, 2 semaines, 1 mois)', max_length=50, verbose_name='Durée')),
                ('moment', models.CharField(blank=True, choices=[('', 'Non spécifié'), ('avant_repas', 'Avant les repas'), ('apres_repas', 'Après les repas'), ('pendant_repas', 'Pendant les repas'), ('coucher', 'Au coucher'), ('reveil', 'Au réveil'), ('douleur', 'En cas de douleur'), ('urgence', "En cas d'urgence"), ('matin', 'Le matin'), ('midi', 'À midi'), ('soir', 'Le soir'), ('quotidien', 'Une fois par jour')], help_text='Contexte ou indication spécifique de la prise', max_length=20, verbose_name='Moment de prise')),
                ('instructions_supplementaires', models.TextField(blank=True, help_text='Instructions particulières pour ce médicament', verbose_name='Instructions supplémentaires')),
                ('quantite_totale', models.PositiveIntegerField(blank=True, help_text="Nombre total d'unités à délivrer au patient", null=True, verbose_name='Quantité totale à délivrer')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_prescriptions', to='patient.consultation')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacyproduct', verbose_name='Médicament')),
            ],
            options={
                'verbose_name': 'Prescription de médicament',
                'verbose_name_plural': 'Prescriptions de médicaments',
                'ordering': ['-date_created'],
            },
        ),
    ]
