# Generated by Django 5.2.3 on 2025-10-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinghistory',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Facture'),
        ),
    ]
