# Generated by Django 5.2.3 on 2025-10-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_add_invoice_number_to_billing_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinghistory',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='N° Facture'),
        ),
    ]
