# Generated by Django 5.2.3 on 2025-10-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_populate_invoice_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinghistory',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date échéance'),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('overdue', 'En retard')], default='draft', max_length=10, verbose_name='Statut'),
        ),
    ]
