# Generated by Django 5.2.3 on 2025-10-22 10:08

from django.db import migrations
from datetime import timedelta


def populate_default_values(apps, schema_editor):
    """Popule les nouveaux champs avec des valeurs par défaut pour les enregistrements existants"""
    BillingHistory = apps.get_model('patient', 'BillingHistory')
    
    # Mettre à jour tous les enregistrements existants
    for billing in BillingHistory.objects.all():
        # Si pas de date d'échéance, définir 30 jours après la date de facturation
        if not billing.due_date:
            billing.due_date = billing.billing_date + timedelta(days=30)
        
        # Si pas de statut, définir 'sent' par défaut
        if not billing.status:
            billing.status = 'sent'
        
        billing.save()


def reverse_populate_default_values(apps, schema_editor):
    """Fonction inverse - ne fait rien car on ne peut pas vraiment annuler"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_add_payment_fields_to_billing_history'),
    ]

    operations = [
        migrations.RunPython(populate_default_values, reverse_populate_default_values),
    ]
