# Generated by Django 5.2.3 on 2025-10-22 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_populate_payment_fields_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.CharField(blank=True, max_length=100, verbose_name='Journal')),
                ('payment_channel', models.CharField(choices=[('cash', 'Espèces'), ('check', 'Chèque'), ('transfer', 'Virement'), ('card', 'Carte bancaire'), ('mobile', 'Mobile money')], default='cash', max_length=20, verbose_name='Canal de paiement')),
                ('payment_mode', models.CharField(choices=[('full', 'Paiement intégral'), ('partial', 'Paiement partiel'), ('advance', 'Acompte')], default='full', max_length=20, verbose_name='Mode de paiement')),
                ('beneficiary_account', models.CharField(blank=True, max_length=100, verbose_name='Compte bancaire du bénéficiaire')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('payment_date', models.DateField(verbose_name='Date de règlement')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='Mémo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patient.billinghistory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
