# Generated by Django 5.2.3 on 2025-10-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_create_payment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinghistory',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('paid', 'Payée'), ('overdue', 'En retard')], default='draft', max_length=10, verbose_name='Statut'),
        ),
    ]
