# Generated by Django 5.2.3 on 2025-10-28 09:43

import django.core.validators
from django.db import migrations, models


def update_gender_values(apps, schema_editor):
    """Convertit les valeurs 'M' (Masculin) en 'H' (Homme)"""
    Patient = apps.get_model('patient', 'Patient')
    Patient.objects.filter(gender='M').update(gender='H')


def reverse_gender_values(apps, schema_editor):
    """Annule la conversion: 'H' -> 'M'"""
    Patient = apps.get_model('patient', 'Patient')
    Patient.objects.filter(gender='H').update(gender='M')


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_update_existing_status_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le N° CIN doit contenir 8 à 20 caractères alphanumériques.', regex='^$|^[A-Z0-9]{8,20}$')], verbose_name='N° CIN'),
        ),
        migrations.RunPython(update_gender_values, reverse_gender_values),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('H', 'H'), ('F', 'F'), ('O', 'Autre')], max_length=1, null=True, verbose_name='Sexe'),
        ),
    ]
