# Generated by Django 5.2.3 on 2025-10-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_alter_patient_cin_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='source',
            field=models.CharField(blank=True, help_text="Source d'acquisition du patient (ex: Réseaux, recommandation, autre)", max_length=200, null=True, verbose_name='Source'),
        ),
    ]
