# Generated by Django 5.2.3 on 2025-10-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_patient_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('medical', 'Médical'), ('administratif', 'Administratif'), ('autre', 'Autre')], default='medical', max_length=20, verbose_name='Type de document')),
                ('document_file', models.FileField(help_text='Document médical du patient', upload_to='medical_documents/%Y/%m/%d/', verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('description', models.CharField(blank=True, help_text='Description optionnelle du document', max_length=255, null=True, verbose_name='Description')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='patient.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Document médical',
                'verbose_name_plural': 'Documents médicaux',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
