# Generated by Django 5.2.3 on 2025-10-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_medicaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medical_notes',
            field=models.TextField(blank=True, help_text='Notes et commentaires concernant le dossier médical', null=True, verbose_name='Notes médicales'),
        ),
    ]
