# Generated by Django 5.2.3 on 2025-10-28 11:23

from django.db import migrations


def fill_empty_source_fields(apps, schema_editor):
    """Remplit le champ source vide pour tous les patients existants"""
    Patient = apps.get_model('patient', 'Patient')
    
    # Compter les patients sans source
    patients_to_update = Patient.objects.filter(source__isnull=True) | Patient.objects.filter(source='')
    count = patients_to_update.count()
    
    if count > 0:
        # Mettre à jour tous les patients avec source vide
        patients_to_update.update(source='Non renseigné')
        print(f"✅ {count} patient(s) mis à jour avec la source 'Non renseigné'")
    else:
        print("ℹ️ Aucun patient à mettre à jour")


def reverse_fill_empty_source_fields(apps, schema_editor):
    """Fonction reverse pour annuler la migration si nécessaire"""
    Patient = apps.get_model('patient', 'Patient')
    # Remettre à vide les sources qui étaient "Non renseigné"
    Patient.objects.filter(source='Non renseigné').update(source='')


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_patient_medical_notes'),
    ]

    operations = [
        migrations.RunPython(fill_empty_source_fields, reverse_fill_empty_source_fields),
    ]
