# Generated by Django 5.2.3 on 2025-10-28 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_fill_empty_source_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.IntegerField(help_text='1er, 2e, 3e...', verbose_name='N° du versement')),
                ('payment_channel', models.CharField(choices=[('cash', 'Espèces'), ('check', 'Chèque')], default='cash', max_length=20, verbose_name='Canal de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_payments', to='patient.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Versement partiel',
                'verbose_name_plural': 'Versements partiels',
                'ordering': ['payment_number'],
            },
        ),
    ]
