# Generated by Django 5.2.3 on 2025-08-20 21:59

import apps.purchases.models.convention
import apps.purchases.models.supplier
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConventionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "purchases_convention_types",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "purchases_country",
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=50)),
                ("abreviation", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "purchases_currency",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "purchases_language",
            },
        ),
        migrations.CreateModel(
            name="PaymentMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "purchases_payment_mode",
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=100)),
                ("valeur", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "db_table": "purchases_tax",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchases.country",
                    ),
                ),
            ],
            options={
                "db_table": "purchases_city",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_company", models.BooleanField(default=True)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("street2", models.CharField(blank=True, max_length=255)),
                ("zip", models.CharField(blank=True, max_length=20)),
                ("email", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("ICE", models.CharField(blank=True, max_length=50)),
                ("RC", models.IntegerField(blank=True, null=True)),
                ("IF", models.IntegerField(blank=True, null=True)),
                ("vat", models.CharField(blank=True, max_length=50)),
                ("RIB", models.CharField(blank=True, max_length=100)),
                ("comment", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.purchases.models.supplier.supplier_logo_path,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="purchases.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="purchases.country",
                    ),
                ),
                (
                    "lang",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="purchases.language",
                    ),
                ),
            ],
            options={
                "db_table": "purchases_supplier",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("date_order", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("waiting", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("partial", "Réception partielle"),
                            ("done", "Fermé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "amount_untaxed",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "amount_tax",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "amount_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "invoice_status",
                    models.CharField(
                        choices=[
                            ("to_invoice", "À facturer"),
                            ("partial", "Partiellement facturé"),
                            ("invoiced", "Totalement facturé"),
                        ],
                        default="to_invoice",
                        max_length=20,
                    ),
                ),
                ("date_planned", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "supplier_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchases.currency",
                    ),
                ),
                (
                    "payment_mode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders",
                        to="purchases.paymentmode",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="purchases.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "purchases_order",
            },
        ),
        migrations.CreateModel(
            name="Convention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("general_conditions", models.TextField()),
                (
                    "attachments",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.purchases.models.convention.convention_upload_path,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("active", "Active"),
                            ("confirmed", "Confirmée"),
                            ("expired", "Expirée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "amount_untaxed",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "amount_tax",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "amount_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "convention_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conventions",
                        to="purchases.conventiontype",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conventions",
                        to="purchases.currency",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conventions",
                        to="purchases.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "purchases_conventions",
                "ordering": ["-date_start"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_qty", models.FloatField()),
                ("price_unit", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_lines",
                        to="purchases.purchaseorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                    ),
                ),
                (
                    "product_uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.unitofmesure",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchases.tax",
                    ),
                ),
            ],
            options={
                "db_table": "purchases_order_line",
            },
        ),
        migrations.CreateModel(
            name="ConventionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_qty", models.FloatField()),
                ("price_unit", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "convention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convention_lines",
                        to="purchases.convention",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchases.tax",
                    ),
                ),
            ],
            options={
                "db_table": "purchases_convention_lines",
            },
        ),
    ]
